server:
  port: 8083

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: INFO
    org.springframework.security: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENTID}
            client-secret: ${GOOGLE_CLIENTSECRET}
            scope: openid,profile,email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs

  cloud:
    gateway:
      routes:
        - id: match-service
          uri: http://${MATCH_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/matches/**
          filters:
            - SetPath=/api/match/{segment}

        - id: news-service
          uri: http://${NEWS_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/news/**
          filters:
            - SetPath=/api/news

        - id: team-service
          uri: http://${TEAM_SERVICE_BASEURL:localhost:8084}
          predicates:
            - Path=/teams/**
          filters:
            - SetPath=/api/team
